# src/content.py

SLIDES = [
    # Slide 1: 封面
    {
        "type": "cover",
        "section": 0,
        "title": "網卡與 OS 層的關係",
        "subtitle": "從 PHY/MAC 到 Windows 驅動堆疊\n——為什麼無法從 Windows 取得 CSI？",
        "author": "",
        "date": "2026-04-07",
        "version": "v4.0",
        "speaker_notes": "大家好，今天的主題是「網卡與 OS 層的關係」。我們會從 RF 工程師最熟悉的 PHY 層出發，一路向上追溯到 Windows 的應用程式層，最後回答一個很多 RF 工程師都碰過的問題：為什麼在 Windows 上無法取得網卡的 CSI 資料？\n\n這份投影片設計給有 PHY/MAC 背景的工程師，所以我不會花太多時間在 RF 基礎，而是聚焦在 OS 軟體層的架構與限制。",
    },
    # Slide 2: 大綱
    {
        "type": "bullets",
        "section": 0,
        "title": "大綱",
        "bullets": [
            "第一段：基礎架構（Slides 3–5）",
            "  · 802.11 RF 信號路徑",
            "  · PHY / MAC 與 CSI",
            "  · OSI 7 層 vs Windows 元件對應",
            "第二段：Windows 驅動堆疊（Slides 6–13）",
            "  · OEM.sys / nwifi.sys / NDIS / WDI",
            "  · CSI 消失點分析",
            "第三段：替代方案（Slides 14–17）",
            "  · Linux 生態 vs Windows 限制",
            "  · 硬體選型建議",
            "第四段：結語與建議（Slides 18–20）",
        ],
        "speaker_notes": "今天的內容分四段。\n\n第一段從 PHY/MAC 基礎出發，確保大家對 CSI 的定義有共同的認知。第二段進入 Windows 的驅動架構，這是大多數 RF 工程師比較陌生的領域。第三段是今天的核心：為什麼 Linux 可以但 Windows 不行，以及有哪些替代方案。最後給出實際的硬體選型建議。\n\n整個演講大約 45 到 60 分鐘，最後留時間 Q&A。",
    },
    # Section Break 1: 基礎架構
    {
        "type": "section_break",
        "section": 1,
        "title": "基礎架構",
        "subtitle": "PHY / MAC / CSI / OSI 對應",
    },
    # Slide 3: 802.11 RF 信號路徑
    {
        "type": "flow",
        "section": 1,
        "title": "802.11 RF 信號路徑",
        "flow_items": [
            ("天線\n(Antenna)", "接收 RF 信號"),
            ("ADC\n類比→數位", "信號數位化"),
            ("OFDM 解調\n(Demodulation)", "子載波分離"),
            ("802.11 Frame\n解碼", "封包還原"),
            ("MAC 層\n處理", "上送至驅動"),
        ],
        "note": "CSI 在 OFDM 解調後即可計算：每個子載波的複數增益（振幅 + 相位）",
        "speaker_notes": "這張圖應該是大家最熟悉的起點。從天線接收到 RF 信號後，經過 ADC 轉換成數位信號，再透過 OFDM 解調把各個子載波分離出來，最後解碼成 802.11 frame。\n\n關鍵點在這裡：CSI 的計算發生在 OFDM 解調這個步驟。每個子載波在解調過程中，NIC 的 DSP 會計算出複數增益，這就是 CSI 的來源。這個資料此時還在 NIC 的韌體裡，尚未進入任何 OS 軟體層。",
    },
    # Slide 4: PHY / MAC 與 CSI
    {
        "type": "two_col",
        "section": 1,
        "title": "PHY / MAC 與 CSI",
        "left_title": "RSSI（傳統方式）",
        "left_bullets": [
            "整體接收功率（單一數值）",
            "單位：dBm",
            "無法區分多路徑效應",
            "精度低，只反映總體信號強度",
        ],
        "right_title": "MAC 層對 CSI 的態度",
        "right_bullets": [
            "MAC 職責：CSMA/CA、ACK、Frame 組裝",
            "",
            "⚠ CSI 不在 MAC 協定範圍",
            "  · PHY 解調後存於 NIC 韌體暫存器",
            "  · MAC 只收到已解調的 802.11 frame",
            "  · CSI 從未進入 NDIS 封包結構",
            "",
            "結論：CSI 旅程的第一個截斷點",
        ],
        "note": "CSI = H(f)：頻域通道矩陣。從 PHY 到 MAC 已無標準傳遞路徑",
        "speaker_notes": "在座各位應該都知道 RSSI，但我還是簡單對比一下。RSSI 是整個頻帶的總接收功率，是一個純量值，單位 dBm。它告訴你「訊號有多強」，但不告訴你「通道長什麼樣子」。\n\nCSI 則是每個 OFDM 子載波的複數增益，包含振幅和相位。802.11n 的情況下，IWL5300 會報告 30 個子載波群組的 CSI。這個資訊豐富多了——你可以從 CSI 重建多路徑傳播特性，這就是為什麼 CSI 可以用於室內定位和手勢辨識，而 RSSI 不行。\n\nCSI 的數學表示是頻域通道矩陣 H(f)，對每對 TX-RX 天線各有一個。",
    },
    # Slide 5: OSI 7 層 vs Windows 元件
    {
        "type": "table",
        "section": 1,
        "title": "OSI 7 層 vs Windows 實際元件對應",
        "headers": ["OSI 層", "標準名稱", "Windows 元件", "備註"],
        "rows": [
            ["L7", "Application", "應用程式 / WinSock API", "send() / recv()"],
            ["L4", "Transport", "tcpip.sys (TCP/UDP)", "連接埠管理"],
            ["L3", "Network", "tcpip.sys (IP)", "路由、IP 封包"],
            ["L2b", "LLC", "ndis.sys (NDIS)", "協定多工/解多工"],
            ["L2a", "MAC", "nwifi.sys + OEM.sys", "802.11 管理"],
            ["L1", "PHY", "NIC 韌體 + 硬體", "RF 信號處理，CSI 在此層"],
        ],
        "note": "CSI 存在於 L1，NDIS 介面從 L2a 開始，兩者之間沒有標準橋接",
        "speaker_notes": "這張表是今天的地圖，後面的所有討論都會對應回這張表。\n\n最重要的觀察：CSI 存在於 L1（PHY 硬體），但 Windows 的軟體介面從 L2a 才開始（nwifi.sys 和 OEM.sys）。L1 和 L2a 之間沒有標準的橋接機制來傳遞 CSI。\n\n右邊的 Windows 元件欄位就是我們接下來要深入討論的每一個元件。請記住這個對應關係。",
    },
    # Section Break 2: Windows 驅動堆疊
    {
        "type": "section_break",
        "section": 2,
        "title": "Windows 驅動堆疊",
        "subtitle": "OEM.sys → nwifi.sys → NDIS → WinSock",
    },
    # Slide 7: Windows 驅動堆疊總覽
    {
        "type": "stack_diagram",
        "section": 2,
        "title": "Windows 網路驅動架構總覽",
        "layers": [
            ("應用程式", "User Mode", "#2d5a27"),
            ("WinSock (ws2_32.dll)", "User Mode", "#2d5a27"),
            ("AFD.sys（Ancillary Function Driver）", "Kernel Mode", "#1a3a6b"),
            ("tcpip.sys（TCP/IP Stack）", "Kernel Mode", "#1a3a6b"),
            ("ndis.sys（NDIS）", "Kernel Mode", "#4a2080"),
            ("nwifi.sys（Native WiFi）", "Kernel Mode", "#4a2080"),
            ("OEM.sys（Miniport Driver）", "Kernel Mode", "#7a1a1a"),
            ("NIC 硬體 + 韌體", "Hardware", "#3a3a00"),
        ],
        "note": "每層只能透過明確定義的介面與相鄰層溝通",
        "speaker_notes": "現在進入 Windows 驅動架構。這張堆疊圖從上到下代表從應用程式到硬體的路徑。\n\n顏色區分了三個層次：綠色是 User Mode（使用者模式），藍色和紫色是 Kernel Mode（核心模式），最底層是硬體。\n\n每一層只能和相鄰層溝通，而且必須透過明確定義的介面。這個設計保證了穩定性，但也意味著 L1 的 PHY 資訊沒有辦法「跳過」中間層直接到應用程式。\n\n接下來我們逐層解釋，重點在紅色的 OEM.sys 和紫色的 nwifi.sys。",
    },
    # Slide 8: OEM.sys 是什麼
    {
        "type": "two_col",
        "section": 2,
        "title": "OEM.sys：網卡廠商 Miniport Driver",
        "left_title": "職責",
        "left_bullets": [
            "直接與 NIC 硬體暫存器溝通（MMIO/PCI）",
            "控制 RF 參數（頻道、頻寬、TX 功率）",
            "管理 DMA 傳輸（TX/RX 封包緩衝）",
            "實作 NDIS Miniport 介面",
            "上報硬體事件給 nwifi.sys",
        ],
        "right_title": "範例（各廠商）",
        "right_bullets": [
            "Intel：iwlwifi（Linux）/ netwtw*.sys（Windows）",
            "Qualcomm/Atheros：ath*.sys",
            "Broadcom：bcmwl*.sys",
            "MediaTek：mt*.sys",
            "",
            "⚠ OEM.sys 是唯一能讀取 CSI 的軟體元件",
            "  但它選擇不向上層暴露此資料",
        ],
        "note": "OEM.sys 是 Windows 驅動堆疊中距離硬體最近的軟體層",
        "speaker_notes": "OEM.sys 是網卡廠商提供的 Miniport Driver，是整個 Windows 網路堆疊中距離硬體最近的軟體元件。\n\n它透過 MMIO 或 PCI 介面直接讀寫網卡的硬體暫存器，可以控制 RF 參數像是頻道和 TX 功率，也負責管理 DMA 傳輸。\n\n右邊的例子列出各廠商的驅動名稱。Intel 在 Linux 上叫 iwlwifi，但在 Windows 上叫 netwtw*.sys，星號代表版本號。\n\n這裡有一個關鍵觀察：OEM.sys 理論上可以讀取 NIC 韌體計算的 CSI 資料，因為它有直接訪問硬體暫存器的能力。問題是它選擇不向上層暴露這個資料。",
    },
    # Slide 9: OEM.sys 資料路徑
    {
        "type": "flow",
        "section": 2,
        "title": "OEM.sys 的資料路徑",
        "flow_items": [
            ("NIC 韌體\n計算 CSI", "儲存於暫存器"),
            ("OEM.sys\nDMA 讀取", "RX 封包緩衝"),
            ("NDIS_RECEIVE\n_NET_BUFFER", "標準封包上報"),
            ("nwifi.sys\n接收", "802.11 frame 處理"),
            ("tcpip.sys\n→ 應用層", "IP 封包"),
        ],
        "note": "CSI 存於 NIC 暫存器，OEM.sys 只將 802.11 frame payload 上報——CSI 從未進入 NDIS 封包結構",
        "speaker_notes": "這張流程圖展示了一個 RX 封包從 NIC 韌體到應用層的路徑。\n\n注意最左邊：NIC 韌體計算 CSI 後，把結果儲存在硬體暫存器。OEM.sys 透過 DMA 讀取 RX 封包緩衝區，但這個緩衝區裡只有 802.11 frame 的內容，不含 CSI。\n\nCSI 從來沒有進入 NDIS_NET_BUFFER 這個標準封包結構。換句話說，CSI 在 OEM.sys 這一步就已經被排除在資料流之外了。\n\n這就是 CSI 消失的根本原因：不是某個軟體元件「擋住」了 CSI，而是 CSI 從一開始就沒有被放進標準的資料傳輸路徑。",
    },
    # Slide 10a: nwifi.sys 職責
    {
        "type": "bullets",
        "section": 2,
        "title": "nwifi.sys：連線管理層（PHY 資訊截斷點）",
        "bullets": [
            "▶ 職責：802.11 連線管理（Native 802.11 架構，Windows 10 起由 WDI 取代但概念相同）",
            "  · 認證（WPA2/WPA3）、漫遊、省電、掃描",
            "",
            "▶ 向上暴露的介面：",
            "  · SSID / RSSI / 連線狀態 / 頻道 / 連線速率",
            "  · Native WiFi API（wlanapi.dll）→ 應用程式",
            "",
            "⚠ 不暴露任何 PHY 層原始資料",
            "  · ❌ CSI、❌ IQ 樣本、❌ 每天線獨立 RSSI",
            "",
            "設計目標是連線管理，不是 RF 量測",
        ],
        "note": "從 nwifi.sys 向上，PHY 層資訊已被永久丟棄",
        "speaker_notes": "nwifi.sys 是 Windows Native WiFi 驅動，職責是管理 802.11 連線狀態。它向上暴露的介面完全沒有任何 PHY 層資訊的傳遞路徑——這是設計目標，不是疏漏。",
    },
    # Slide 12a: NDIS OID 機制
    {
        "type": "bullets",
        "section": 2,
        "title": "NDIS 無 CSI 的根本原因",
        "bullets": [
            "NDIS 設計目標：跨廠商通用介面",
            "  · 任何協定 × 任何網卡 = 最大公約數",
            "",
            "OID 機制提供：SSID / RSSI / 掃描 / 統計",
            "❌ 無任何 OID 定義 CSI 查詢",
            "",
            "▶ 為什麼無法標準化 CSI？",
            "  · Intel 5300：30 個子載波群組",
            "  · Atheros AR9380：56 個子載波",
            "  · 格式完全不同，無法取最大公約數",
            "",
            "結論：通用性的代價 = 丟棄廠商私有 PHY 細節",
        ],
        "note": "NDIS 的「通用性」正是 CSI 無法取得的根本原因",
        "speaker_notes": "NDIS 的核心設計目標是跨廠商通用性，但 CSI 是廠商私有 PHY 細節，不同廠商格式完全不同。無法取最大公約數，所以 NDIS 根本沒有嘗試。",
    },
    # Slide 13: WDI
    {
        "type": "two_col",
        "section": 2,
        "title": "WDI：Windows 10+ 新驅動模型",
        "left_title": "WDI 改變了什麼",
        "left_bullets": [
            "WLAN Device Driver Interface（WDI）",
            "Win10 引入，取代部分 NDIS WiFi 介面",
            "將驅動分為：",
            "  · IHV 元件（UMDF，User Mode）",
            "  · WDI 框架（KMDF，Kernel Mode）",
            "降低藍屏風險（User Mode crash 不致命）",
            "簡化 IHV 驅動開發",
        ],
        "right_title": "WDI 對 CSI 的影響",
        "right_bullets": [
            "❌ WDI Task/Property 定義中",
            "   同樣沒有 CSI 相關介面",
            "",
            "WDITASK 清單（部分）：",
            "  · TaskScan",
            "  · TaskConnect",
            "  · TaskDisconnect",
            "  · TaskSendRequest",
            "",
            "→ 架構更新，但 CSI 缺席問題未解決",
        ],
        "note": "WDI 是架構改進，不是 PHY 資料暴露的嘗試",
        "speaker_notes": "Windows 10 引入了 WDI 作為新的 WiFi 驅動模型。WDI 把驅動分成兩部分：IHV 廠商負責的 User Mode 元件，和 WDI 框架的 Kernel Mode 元件。\n\n這個架構的優點是：User Mode 的 crash 不會導致藍屏，大幅提升系統穩定性，也簡化了廠商的驅動開發。\n\n但是——WDI 的 Task 和 Property 定義完全沒有包含 CSI 相關的介面。WDI 是架構上的改進，不是解決 CSI 取得問題的嘗試。所以即使升級到 WDI 模型，CSI 依然無法取得。",
    },
    # Slide 14: CSI 消失點分析
    {
        "type": "stack_diagram_annotated",
        "section": 2,
        "title": "CSI 消失點分析",
        "layers": [
            ("應用程式 / WinSock", "無法感知 CSI 存在", "normal"),
            ("tcpip.sys", "只處理 IP 封包", "normal"),
            ("ndis.sys（NDIS）", "無 CSI OID 定義", "warning"),
            ("nwifi.sys", "丟棄所有 PHY metadata", "danger"),
            ("OEM.sys", "能讀取 CSI，但不上報", "danger"),
            ("NIC 韌體 + 硬體", "CSI 計算並儲存於此", "source"),
        ],
        "note": "CSI 消失於 OEM.sys ↔ nwifi.sys 介面：OEM.sys 有能力讀取但選擇不轉發，nwifi.sys 也不要求",
        "speaker_notes": "這是今天的核心投影片。讓我們總結 CSI 在哪裡消失。\n\n橙色和紅色標注的兩個元件是關鍵：OEM.sys 和 nwifi.sys。\n\nOEM.sys 有能力讀取 CSI（因為它可以直接訪問 NIC 硬體暫存器），但它不上報給 nwifi.sys。nwifi.sys 也從未向 OEM.sys 請求 CSI 資料。這個邊界就是 CSI 消失的地方。\n\n再往上，ndis.sys 沒有 CSI 的 OID 定義，tcpip.sys 只看到 IP 封包，應用程式完全感知不到 CSI 的存在。\n\n結論：CSI 的消失是多層架構決策累積的結果，每一層都有其合理性。",
    },
    # Section Break 3: 替代方案
    {
        "type": "section_break",
        "section": 3,
        "title": "替代方案",
        "subtitle": "Linux 生態 vs Windows 限制",
    },
    # Slide 15: 為什麼 Linux 可以
    {
        "type": "two_col",
        "section": 3,
        "title": "為什麼 Linux 可以取得 CSI？",
        "left_title": "Linux 驅動架構",
        "left_bullets": [
            "cfg80211：802.11 設定框架",
            "mac80211：軟體 MAC 實作",
            "nl80211：Netlink 介面（用戶空間↔核心）",
            "",
            "關鍵差異：開源驅動",
            "  · iwlwifi（Intel）可修改",
            "  · ath9k（Atheros）可修改",
            "  · brcmfmac（Broadcom）可 patch 韌體",
            "",
            "debugfs 介面：",
            "  /sys/kernel/debug/ieee80211/",
            "  部分驅動在此暴露 CSI 原始資料",
        ],
        "right_title": "Windows 的根本差異",
        "right_bullets": [
            "✗ OEM.sys 為閉源二進位",
            "✗ NDIS 介面固定，無擴充 CSI 的機制",
            "✗ 無等同 debugfs 的 PHY 資料介面",
            "✗ 韌體修改需要 WHQL 簽章",
            "",
            "→ Linux 的可行性來自",
            "  開源 + 可修改驅動 + 彈性的核心介面",
            "  不是 Windows 的「bug」，是設計哲學差異",
        ],
        "note": "Linux 的可行性來自開源生態，不是 Windows 的設計缺陷",
        "speaker_notes": "現在我們來看為什麼 Linux 可以取得 CSI。\n\nLinux 的關鍵優勢是開源。iwlwifi、ath9k、brcmfmac 這些驅動都是開源的，研究人員可以直接修改驅動程式碼，甚至修改 NIC 韌體。debugfs 提供了一個核心介面，讓驅動可以暴露任意的除錯資料，包括 CSI。\n\n右邊列出了 Windows 的根本差異：OEM.sys 是閉源二進位，不可修改；NDIS 介面固定，沒有擴充機制；韌體修改需要 WHQL 認證簽章。\n\n這不是 Windows 的 bug，而是商業產品（Windows）vs 開源生態（Linux）的架構哲學差異。",
    },
    # Slide 17: 現代 CSI 工具生態
    {
        "type": "table",
        "section": 3,
        "title": "現代 CSI 工具生態（全部 Linux-only）",
        "headers": ["工具", "硬體", "標準", "頻寬", "特色"],
        "rows": [
            ["PicoScenes", "Intel AX200/AX210", "802.11a/g/n/ac/ax", "20–160 MHz", "最完整，商業支援"],
            ["FeitCSI", "Intel AX200/AX210", "802.11a/g/n/ac/ax", "20–160 MHz", "開源，CSI 注入"],
            ["IAX", "Intel AX200/201/210/211", "802.11ax", "20–160 MHz", "學術研究用"],
            ["Nexmon CSI", "Broadcom/Cypress", "802.11a/g/n/ac", "20–80 MHz", "Raspberry Pi 支援"],
            ["Atheros-CSI-Tool", "AR9380（ath9k）", "802.11n", "20/40 MHz", "OpenWRT 支援"],
            ["linux-80211n-csitool", "Intel IWL5300", "802.11n", "20/40 MHz", "最早的工具，歷史性"],
        ],
        "note": "所有工具均僅支援 Linux——這直接說明了為什麼 Windows 無法取得 CSI",
        "speaker_notes": "這是目前（2026 年）的現代 CSI 工具生態。\n\nPicoScenes 是目前功能最完整的平台，支援 Intel AX200/AX210，可以取得 802.11ax 格式的 CSI，最寬支援 160 MHz。它有商業支援，適合需要穩定維護的研究團隊。\n\nFeitCSI 是開源替代方案，功能相近，也支援 CSI 注入，可以用於主動量測。\n\n這張表的最右欄「平台」請注意：全部都是 Linux。這個事實本身就是今天演講的核心論點之一——所有成熟的 CSI 工具都選擇 Linux，因為 Windows 的架構限制讓這件事在 Windows 上無法實現。",
    },
    # Slide 18: Windows 替代方案比較
    {
        "type": "table",
        "section": 3,
        "title": "Windows 替代方案比較",
        "headers": ["方案", "技術難度", "CSI 完整度", "維護成本", "建議"],
        "rows": [
            ["Raw Packet Capture\n(WinPcap/Npcap)", "★☆☆☆", "❌ 無 CSI", "低", "僅封包分析"],
            ["OEM 私有 IOCTL\n(逆向 OEM.sys)", "★★★★", "⚠ 不穩定", "極高", "不建議"],
            ["雙系統 Linux（推薦）", "★★☆☆", "✅ 完整", "低", "最佳方案"],
            ["Linux Live USB\n(FeitCSI)", "★☆☆☆", "✅ 完整", "低", "快速上手"],
        ],
        "note": "建議：Intel AX200 + 雙系統 Linux + PicoScenes/FeitCSI",
        "speaker_notes": "四種方案快速比較。Raw Packet Capture 最簡單但無 CSI。OEM IOCTL 風險極高。雙系統和 Live USB 都能取到完整 CSI，推薦雙系統。",
    },
    # Slide 22: 硬體選型
    {
        "type": "table",
        "section": 3,
        "title": "支援 CSI 的硬體選型",
        "headers": ["網卡型號", "晶片", "標準", "CSI 工具", "平台"],
        "rows": [
            ["Intel WiFi Link 5300", "IWL5300", "802.11n", "linux-80211n-csitool", "Linux（舊）"],
            ["Intel Wi-Fi 6 AX200", "AX200", "802.11ax", "PicoScenes / FeitCSI", "Linux"],
            ["Intel Wi-Fi 6E AX210", "AX210", "802.11ax（6GHz）", "PicoScenes / FeitCSI", "Linux"],
            ["Atheros AR9380", "AR9380", "802.11n", "Atheros-CSI-Tool", "Linux / OpenWRT"],
            ["Broadcom BCM4339", "BCM4339", "802.11ac", "Nexmon CSI", "Android / RPi"],
            ["Raspberry Pi 4 (RPi)", "CYW43455 (原BCM43455)", "802.11ac", "Nexmon CSI", "Linux（RPi OS）"],
        ],
        "note": "採購建議：Intel AX200 M.2 網卡 + Linux 雙系統 = 最易取得的 CSI 研究平台",
        "speaker_notes": "這張表列出目前（2026 年）有明確 CSI 工具支援的網卡。\n\n如果你要買新硬體，Intel AX200 M.2 是最容易取得、工具支援最完整的選擇。它便宜（通常 500 到 1000 台幣），支援 802.11ax，PicoScenes 和 FeitCSI 都支援它。買 M.2 版本可以裝在筆電或桌機，或者用 M.2 轉 PCIe 轉接卡。\n\n如果你有 Raspberry Pi，BCM43455 晶片已經內建，Nexmon CSI 直接支援，不需要額外購買硬體，非常適合做嵌入式 CSI 採集節點。\n\nAtheros AR9380 在 OpenWRT 路由器上很常見，適合布署多點 CSI 量測環境。\n\n請避免購買沒有在這份清單上的網卡，除非你願意自己移植驅動。",
    },
    # Section Break 4: 結語與建議
    {
        "type": "section_break",
        "section": 4,
        "title": "結語與建議",
        "subtitle": "硬體選型 + 環境建議",
    },
    # Slide 23: 架構限制總結
    {
        "type": "stack_diagram_annotated",
        "section": 4,
        "title": "完整架構總覽：CSI 的旅程",
        "layers": [
            ("應用程式", "只能用 WinSock，看不到 PHY", "normal"),
            ("NDIS / tcpip.sys", "無 CSI OID，協定通用化", "warning"),
            ("nwifi.sys", "802.11 管理，丟棄 PHY metadata", "danger"),
            ("OEM.sys（唯一機會）", "能讀 CSI，但介面不暴露", "danger"),
            ("NIC 韌體", "CSI 在此計算完成", "source"),
            ("PHY 硬體 + RF 電路", "OFDM 解調，子載波分析", "source"),
        ],
        "note": "Windows 架構的每一層都有合理的設計動機，但合力造成了 CSI 無法取得的結果",
        "speaker_notes": "讓我們用這張總結圖回顧整個旅程。\n\n從最下面的 PHY 硬體開始，OFDM 解調計算出 CSI，儲存在 NIC 韌體的暫存器中。NIC 韌體計算完成後，這個資訊就在這裡等待被讀取。\n\nOEM.sys 是唯一有能力讀取這個資料的軟體元件，但它的設計目標不包含上報 CSI，所以它沒有這樣做。\n\n往上的每一層，從 nwifi.sys 到 NDIS 到應用程式，都沒有任何機制可以取得 CSI。每一層都有合理的設計動機，但合在一起的結果就是 CSI 無法從應用層存取。\n\n這不是一個單一決策造成的問題，而是多層架構設計累積的結果。",
    },
    # Slide 24a: 建議
    {
        "type": "bullets",
        "section": 4,
        "title": "給 RF 工程師的建議",
        "bullets": [
            "1. 選硬體先確認 CSI 工具支援",
            "   → Intel AX200/AX210 = 目前最佳選擇",
            "",
            "2. 優先 Linux 環境採集 CSI",
            "   → PicoScenes（商業支援）或 FeitCSI（開源）",
            "   → 雙系統：Linux 採集，Windows 後處理",
            "",
            "3. 避免的坑",
            "   ❌ OEM 私有 IOCTL（每次驅動更新後失效）",
            "   ❌ VM 取 CSI（時序精度受 Hypervisor 影響）",
            "   ❌ 未在支援清單上的網卡",
        ],
        "speaker_notes": "基於今天的內容，給各位三點具體建議。希望能幫助大家避免走彎路，直接使用最有效的工具。",
    },
    # Slide 25: Q&A / 參考資料
    {
        "type": "references",
        "section": 4,
        "title": "參考資料",
        "refs": [
            "[1] D. Halperin et al., Tool Release: Gathering 802.11n Traces with CSI, ACM SIGCOMM CCR, Vol. 41, No. 1, 2011. -> linux-80211n-csitool",
            "[2] M. Schulz et al., Nexmon: The C-based Firmware Patching Framework -- seemoo-lab/nexmon_csi",
            "[3] Z. Jiang, PicoScenes: Enabling Modern Wi-Fi ISAC Research -- ps.zpj.io",
            "[4] KuskoSoft, FeitCSI: 802.11 CSI Tool -- feitcsi.kuskosoft.com",
            "[5] Y. Xie et al., Atheros CSI Tool for 802.11n NICs -- xieyaxiongfly/Atheros-CSI-Tool",
            "[6] Microsoft Docs, WDI Miniport Driver Design Guide -- learn.microsoft.com",
            "[7] Microsoft Docs, NDIS Network Interface Architecture -- learn.microsoft.com",
            "[8] Gi-z, CSIKit: Python CSI Processing Tools -- github.com/Gi-z/CSIKit",
        ],
        "qanda": "Q&A",
        "speaker_notes": "以上是今天的所有內容。\n\n如果你要開始 CSI 研究，推薦先看 PicoScenes 的文件（ps.zpj.io），它提供了很完整的 setup guide。FeitCSI（feitcsi.kuskosoft.com）是開源替代方案，適合想要自己修改的研究者。CSIKit 是一個 Python 函式庫，可以解析多種 CSI 工具的輸出格式，方便資料分析。\n\n有任何問題嗎？",
    },
]
